export const REQUEST_COMPANY_LIST = 'REQUEST_COMPANY_LIST';
export const REQUEST_COMPANY_LIST_SUCCESS = 'REQUEST_COMPANY_LIST_SUCCESS';
export const REQUEST_COMPANY_LIST_ERROR = 'REQUEST_COMPANY_LIST_ERROR';

export const REQUEST_COMPANY_INFO = 'REQUEST_COMPANY_INFO';
export const REQUEST_COMPANY_INFO_SUCCESS = 'REQUEST_COMPANY_INFO_SUCCESS';
export const REQUEST_COMPANY_INFO_ERROR = 'REQUEST_COMPANY_INFO_ERROR';

export const REQUEST_EMPLOYEE_LIST = 'REQUEST_EMPLOYEE_LIST';
export const REQUEST_EMPLOYEE_LIST_SUCCESS = 'REQUEST_EMPLOYEE_LIST_SUCCESS';
export const REQUEST_EMPLOYEE_LIST_ERROR = 'REQUEST_EMPLOYEE_LIST_ERROR';

export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';
export const ADD_EMPLOYEE_SUCCESS = 'ADD_EMPLOYEE_SUCCESS';
export const ADD_EMPLOYEE_ERROR = 'ADD_EMPLOYEE_ERROR';

export const UPDATE_EMPLOYEE = 'UPDATE_EMPLOYEE';
export const UPDATE_EMPLOYEE_SUCCESS = 'UPDATE_EMPLOYEE_SUCCESS';
export const UPDATE_EMPLOYEE_ERROR = 'UPDATE_EMPLOYEE_ERROR';

export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';
export const DELETE_EMPLOYEE_SUCCESS = 'DELETE_EMPLOYEE_SUCCESS';
export const DELETE_EMPLOYEE_ERROR = 'DELETE_EMPLOYEE_ERROR';










export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';
